steps:
  # Step 1: Build the Docker image with the secrets passed as build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/myran-art-00002-f5c/myran-art:${SHORT_SHA}'
      - '--build-arg'
      - 'DATO_TOKEN=$_DATO_TOKEN'
      - '--build-arg'
      - 'DATO_PREVIEW=$_DATO_PREVIEW'
      - '.'
    secretEnv: ['_DATO_TOKEN', '_DATO_PREVIEW']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myran-art-00002-f5c/myran-art:${SHORT_SHA}']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'myran-art-service'
      - '--image'
      - 'gcr.io/myran-art-00002-f5c/myran-art:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'DATO_TOKEN=$_DATO_TOKEN,DATO_PREVIEW=$_DATO_PREVIEW'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: 'projects/myran-art-00002-f5c/secrets/DATO_TOKEN/versions/latest'
      env: '_DATO_TOKEN'
    - versionName: 'projects/myran-art-00002-f5c/secrets/DATO_PREVIEW/versions/latest'
      env: '_DATO_PREVIEW'

images:
  - 'gcr.io/myran-art-00002-f5c/myran-art:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
