steps:
  # Build Docker image and pass in secrets as build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'DATO_TOKEN="${_DATO_TOKEN}"'
      - '--build-arg'
      - 'DATO_PREVIEW="${_DATO_PREVIEW}"'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/anneli-art:${COMMIT_SHA}'
      - '.'
    secretEnv: ['DATO_TOKEN', 'DATO_PREVIEW']

secrets:
  - secretEnv:
      DATO_TOKEN: projects/anneli-art-00002-f5c/secrets/DATO_TOKEN/versions/latest
      DATO_PREVIEW: projects/anneli-art-00002-f5c/secrets/DATO_PREVIEW/versions/latest

images:
  - 'gcr.io/${PROJECT_ID}/anneli-art:${COMMIT_SHA}'
