steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/anneli-art-00002-f5c/anneli-art:$SHORT_SHA'
      - '.'
    secretEnv: ['DATO_TOKEN', 'DATO_PREVIEW']

  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/anneli-art-00002-f5c/anneli-art:$SHORT_SHA']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'anneli-art-service'
      - '--image'
      - 'gcr.io/anneli-art-00002-f5c/anneli-art:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'DATO_TOKEN=${_DATO_TOKEN},DATO_PREVIEW=${_DATO_PREVIEW}'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: 'projects/anneli-art-00002-f5c/secrets/DATO_TOKEN/versions/latest'
      env: '_DATO_TOKEN'
    - versionName: 'projects/anneli-art-00002-f5c/secrets/DATO_PREVIEW/versions/latest'
      env: '_DATO_PREVIEW'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/anneli-art-00002-f5c/anneli-art:$SHORT_SHA'
# availableSecrets:
#   secretManager:
#     - versionName: projects/anneli-art-00002-f5c/secrets/DATO_TOKEN/versions/latest
#       env: 'DATO_TOKEN'
#     - versionName: projects/anneli-art-00002-f5c/secrets/DATO_PREVIEW/versions/latest
#       env: 'DATO_PREVIEW'
# images:
#   - 'gcr.io/${PROJECT_ID}/anneli-art:${COMMIT_SHA}'
