steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/myran-art/myran-art:${SHORT_SHA}'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myran-art/myran-art:${SHORT_SHA}']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'myran-art-service'
      - '--image'
      - 'gcr.io/myran-art/myran-art:${SHORT_SHA}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--update-env-vars'
      - 'DATO_TOKEN=${_DATO_TOKEN},DATO_PREVIEW=${_DATO_PREVIEW}'
      - '--allow-unauthenticated'

# Define substitution variables and their corresponding secrets
substitutions:
  _DATO_TOKEN: 'projects/myran-art/secrets/DATO_TOKEN/versions/latest'
  _DATO_PREVIEW: 'projects/myran-art/secrets/DATO_PREVIEW/versions/latest'

images:
  - 'gcr.io/myran-art/myran-art:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
