steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/myran-art/myran-art:$SHORT_SHA', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myran-art/myran-art:$SHORT_SHA']

  # Deploy the Docker image to Google Cloud Run with the environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'myran-art-service'
      - '--image'
      - 'gcr.io/myran-art/myran-art:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--update-env-vars'
      - 'DATO_TOKEN=${_DATO_TOKEN},DATO_PREVIEW=${_DATO_PREVIEW}'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/myran-art/myran-art:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
