steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/anneli-art:${SHORT_SHA}'
      - '.'
      - '--build-arg'
      - 'DATO_TOKEN="${_DATO_TOKEN}"'
      - '--build-arg'
      - 'DATO_PREVIEW="${_DATO_PREVIEW}"'
    secretEnv: ['_DATO_TOKEN', '_DATO_PREVIEW']

  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/anneli-art:${SHORT_SHA}']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'anneli-art-service'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/anneli-art:${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'DATO_TOKEN="${_DATO_TOKEN}",DATO_PREVIEW="${_DATO_PREVIEW}"'
      - '--allow-unauthenticated'

secrets:
  - kmsKeyName: projects/anneli-art-00002-f5c/locations/global/keyRings/my-keyring/cryptoKeys/my-key
    secretEnv:
      _DATO_TOKEN: projects/anneli-art-00002-f5c/secrets/DATO_TOKEN/versions/latest
      _DATO_PREVIEW: projects/anneli-art-00002-f5c/secrets/DATO_PREVIEW/versions/latest

images:
  - 'gcr.io/${PROJECT_ID}/anneli-art:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
